class IngredientField:
    INGREDIENT_NAME_LENGTH = 200
    INGREDIENT_UNIT_LENGTH = 200


class TagField:
    TAG_COLOR_LENGTH = 7
    TAG_NAME_LENGTH = 200


class RecipeField:
    RECIPE_INGREDIENT_MIN = 1
    RECIPE_INGREDIENT_MAX = 10000
    RECIPE_NAME_LENGTH = 200
    RECIPE_COOK_TIME_MIN = 1
    RECIPE_COOK_TIME_MAX = 24 * 60
